[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/var/log/nginx_stdout.log
stderr_logfile=/var/log/nginx_stderr.log
priority=10

[program:blue-server]
command=node /app/blue-server/app.js
autostart=true
autorestart=true
stdout_logfile=/var/log/blue_server.log
stderr_logfile=/var/log/blue_server_error.log
environment=NODE_ENV="production"
priority=20

[program:green-server]
command=node /app/green-server/app.js
autostart=true
autorestart=true
stdout_logfile=/var/log/green_server.log
stderr_logfile=/var/log/green_server_error.log
environment=NODE_ENV="production"
priority=20

[inet_http_server]
port=127.0.0.1:9001

[supervisorctl]
serverurl=http://127.0.0.1:9001

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface
