# AWS CodeDeploy Application Specification
# Enhanced Blue-Green Deployment with ALB Integration
# Version: 3.0 - Improved with graceful shutdown and comprehensive hooks
# Based on AWS Best Practices and 개선문서.md recommendations

version: 0.0
os: linux

files:
  # Application source code and configuration
  - source: /
    destination: /opt/bluegreen-app
    overwrite: true
    
permissions:
  # Set proper permissions for application files
  - object: /opt/bluegreen-app
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - file
      - directory
      
  # Make scripts executable
  - object: /opt/bluegreen-app/scripts
    pattern: "**/*.sh"
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - file
      
  # Log directory permissions
  - object: /opt/bluegreen-app/logs
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - directory

hooks:
  # 1. Prepare for traffic blocking (new hook for graceful pre-drain)
  BeforeBlockTraffic:
    - location: scripts/codedeploy/before-block-traffic.sh
      timeout: 600
      runas: root

  # 2. Stop running applications and services with graceful shutdown
  ApplicationStop:
    - location: scripts/codedeploy/stop-app.sh
      timeout: 600
      runas: root
      
  # 3. Prepare environment before installation
  BeforeInstall:
    - location: scripts/codedeploy/before-install.sh
      timeout: 600
      runas: root
      
  # 4. Install dependencies and prepare application
  AfterInstall:
    - location: scripts/codedeploy/after-install.sh
      timeout: 600
      runas: ec2-user
      
  # 5. Start applications and services with health checking
  ApplicationStart:
    - location: scripts/codedeploy/start-app.sh
      timeout: 600
      runas: ec2-user
      
  # 6. Comprehensive service validation
  ValidateService:
    - location: scripts/codedeploy/validate-service.sh
      timeout: 300
      runas: ec2-user