version: '3.8'

services:
  blue-green-deployment:
    build: .
    container_name: blue-green-nginx
    ports:
      - "80:80"     # 메인 프록시
      - "8080:8080" # 관리자 인터페이스
      - "3001:3001" # Blue 서버 (직접 접근용)
      - "3002:3002" # Green 서버 (직접 접근용)
      - "9000:9000" # API 서버 (디버깅용)
    volumes:
      - nginx_logs:/var/log/nginx
      # 설정 파일들은 Dockerfile에서 복사하므로 볼륨 마운트 제거
      # - ./nginx.conf:/etc/nginx/nginx.conf:ro  
      # - ./conf.d:/etc/nginx/conf.d
      # - ./admin.html:/var/www/html/index.html:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  nginx_logs: